apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crud-pvc
  namespace: laravel-crud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
