apiVersion: v1
kind: PersistentVolume
metadata:
  name: crud-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql
