apiVersion: apps/v1
kind: Deployment
metadata: 
 name: crud-deployment
 namespace: laravel-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-crud
  template:
    metadata:
      labels:
        app: laravel-crud
    spec:
      serviceAccountName: laravel-sa
      containers:
        - name: laravel-crud-container
          image: sourav1911/laravel-app:v2
          imagePullPolicy: Always
          ports: 
          - containerPort: 80

          envFrom:
            - configMapRef:
                name: crud-config

          env:
           - name: DB_PASSWORD
             valueFrom:
              secretKeyRef:
               name: mysql-secret
               key: MYSQL_ROOT_PASSWORD
