version: "3.8"

volumes:
    laravel-mysql-data:
    

networks:
    laravel-network:
      driver: bridge

services:

  


  mysql:
   image: mysql:8
   container_name: mysql-container
   restart: unless-stopped
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: laravel
   volumes:
    - laravel-mysql-data:/var/lib/mysql
   networks:
    - laravel-network


  app:
    image: sourav1911/laravel-app:v2
    container_name: laravel-container
    ports:
       - "8000:80"
    networks:
       - laravel-network
    depends_on:
       - mysql



